name: flutter_app1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
author: Xie

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.4.1
  cloud_firestore: ^5.4.1
  firebase_auth: ^5.3.1
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.0
  date_format: ^2.0.7
  firebase_storage: ^12.3.3
  image_picker: ^1.0.4
  photo_manager: ^3.5.0
  uuid: ^4.0.0
  video_player: ^2.8.1
  flutter_staggered_grid_view: ^0.7.0  
  intl: ^0.19.0
  
  http: ^1.4.0
  url_launcher: ^6.2.5
  shared_preferences: ^2.3.0
  webview_flutter: ^4.9.0
  fl_chart: ^0.69.0
  flutter_secure_storage: ^9.0.0

  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^17.0.0

  
  flutter_map: ^6.0.0
  latlong2: ^0.9.0
  geolocator: ^10.0.0
  geolocator_android: 4.6.1
  youtube_player_flutter: ^9.1.1
  flutter_inappwebview: ^6.0.0 
  permission_handler: ^11.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets\images\incline_chest_press.jpeg
    - assets\images\ChestFly.jpg
    - assets\images\ChestPress.jpg
    - assets\images\InclineChestFly.jpg
    - assets\images\DeclineChestPress.jpg
    - assets\images\DeclineChestFly.jpg
    - assets\images\LatPulldown.jpg
    - assets\images\SeatedRow.jpg
    - assets\images\Deadlift.jpg
    - assets\images\BentOverRow.jpg
    - assets\images\PullUp.jpg
    - assets\images\Squat.jpg
    - assets\images\Lunge.jpg
    - assets\images\LegPress.jpg
    - assets\images\RomanianDeadlift.jpg
    - assets\images\ShoulderPress.jpg
    - assets\images\LateralRaise.jpg
    - assets\images\FrontRaise.jpg
    - assets\images\RearDeltFly.jpg
    - assets\images\Crunch.jpg
    - assets\images\Plank.jpg
    - assets\images\LegRaise.jpg
    - assets\images\BicycleCrunch.jpg
    - assets\images\BicepCurl.jpg
    - assets\images\TricepDip.jpg
    - assets\images\HammerCurl.jpg
    - assets\images\TricepExtension.jpg
