// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-XAD46z8sPvcHc6KJiOBbD3S31Y18OwU',
    appId: '1:671231395414:web:0dbe3d29c1b247f2aaddf7',
    messagingSenderId: '671231395414',
    projectId: 'flutter-app1-384ff',
    authDomain: 'flutter-app1-384ff.firebaseapp.com',
    storageBucket: 'flutter-app1-384ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBem3uBVV1Z60ClKRSqO1yx70fxViHySmQ',
    appId: '1:671231395414:android:875acb86d3d32599aaddf7',
    messagingSenderId: '671231395414',
    projectId: 'flutter-app1-384ff',
    storageBucket: 'flutter-app1-384ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Ai8o_UeM-qMCxk9N7OOe13V4em50Asg',
    appId: '1:671231395414:ios:60843d88cebd5b18aaddf7',
    messagingSenderId: '671231395414',
    projectId: 'flutter-app1-384ff',
    storageBucket: 'flutter-app1-384ff.appspot.com',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Ai8o_UeM-qMCxk9N7OOe13V4em50Asg',
    appId: '1:671231395414:ios:60843d88cebd5b18aaddf7',
    messagingSenderId: '671231395414',
    projectId: 'flutter-app1-384ff',
    storageBucket: 'flutter-app1-384ff.appspot.com',
    iosBundleId: 'com.example.flutterApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-XAD46z8sPvcHc6KJiOBbD3S31Y18OwU',
    appId: '1:671231395414:web:573e414d972c6e86aaddf7',
    messagingSenderId: '671231395414',
    projectId: 'flutter-app1-384ff',
    authDomain: 'flutter-app1-384ff.firebaseapp.com',
    storageBucket: 'flutter-app1-384ff.appspot.com',
  );

}